#!/usr/bin/env bash
#
# Build an UNSIGNED release .ipa of Opal for sideloading via AltStore / SideStore.
#
# AltStore re-signs the .ipa with your own (free) Apple ID at install time, so we
# deliberately build with codesigning disabled here. No paid Apple Developer
# account or DEVELOPMENT_TEAM is required.
#
# Output: build/altstore/Opal.ipa
#
# Usage:
#   ./scripts/build_ipa.sh                 # standalone / mock backend (default)
#
#   # point at a real Loop Pal backend, via individual env vars:
#   PAL_BASE_URL=https://pal.example.com \
#   PAL_PROVISIONING_KEY=secret \
#     ./scripts/build_ipa.sh
#
#   # ...or via a --dart-define-from-file JSON (same format Flutter expects),
#   # e.g. dart_defines/prod.json: {"PAL_BASE_URL": "...", "PAL_PROVISIONING_KEY": "..."}
#   ./scripts/build_ipa.sh dart_defines/prod.json
#   PAL_CONFIG=dart_defines/prod.json ./scripts/build_ipa.sh
#
# If both are given, env vars are applied last and override file values.
#
set -euo pipefail

# Homebrew flutter isn't always on PATH in non-login shells.
export PATH="/opt/homebrew/bin:$PATH"

cd "$(dirname "$0")/.."
ROOT="$(pwd)"
APP="build/ios/iphoneos/Runner.app"
OUT_DIR="build/altstore"

DEFINES=()

# A --dart-define-from-file JSON, from the first arg or $PAL_CONFIG.
CONFIG_FILE="${1:-${PAL_CONFIG:-}}"
if [[ -n "$CONFIG_FILE" ]]; then
  [[ -f "$CONFIG_FILE" ]] || { echo "Config file not found: $CONFIG_FILE" >&2; exit 1; }
  DEFINES+=(--dart-define-from-file="$CONFIG_FILE")
  echo "==> Config: $CONFIG_FILE"
fi

# Individual env vars; applied after the file so they override its values.
if [[ -n "${PAL_BASE_URL:-}" ]]; then
  DEFINES+=(--dart-define=PAL_BASE_URL="$PAL_BASE_URL")
  echo "==> Backend: $PAL_BASE_URL"
  [[ -n "${PAL_PROVISIONING_KEY:-}" ]] && \
    DEFINES+=(--dart-define=PAL_PROVISIONING_KEY="$PAL_PROVISIONING_KEY")
elif [[ -z "$CONFIG_FILE" ]]; then
  echo "==> Backend: standalone / mock (no PAL_BASE_URL or config file set)"
fi

# --- Widget config (the half --dart-define can't reach) -----------------------
# dart-defines feed the Dart/app side only. The OpalWidgets extension reads
# PAL_BASE_URL / PAL_PROVISIONING_KEY from its Info.plist, which substitutes from
# Xcode *build settings* — not dart-defines. Mirror the resolved values into a
# gitignored xcconfig that Debug/Release.xcconfig optionally include, so the
# widget talks to the same backend the app does. Resolve from the JSON file
# first, then let env vars override (same precedence as the dart-defines above).
XCCONFIG="ios/Flutter/PalConfig.generated.xcconfig"
read_json_key() {  # $1=file $2=key -> value on stdout ("" if absent/unreadable)
  python3 -c 'import json,sys
try:
    print(json.load(open(sys.argv[1])).get(sys.argv[2], ""))
except Exception:
    pass' "$1" "$2"
}
W_BASE_URL=""; W_KEY=""
if [[ -n "$CONFIG_FILE" ]]; then
  W_BASE_URL="$(read_json_key "$CONFIG_FILE" PAL_BASE_URL)"
  W_KEY="$(read_json_key "$CONFIG_FILE" PAL_PROVISIONING_KEY)"
fi
[[ -n "${PAL_BASE_URL:-}" ]] && W_BASE_URL="$PAL_BASE_URL"
[[ -n "${PAL_PROVISIONING_KEY:-}" ]] && W_KEY="$PAL_PROVISIONING_KEY"

if [[ -n "$W_BASE_URL" ]]; then
  # xcconfig starts a comment at //, so a raw URL loses everything from "//"
  # on. Break the token with $() — it expands to empty, so the resolved build
  # setting is byte-for-byte the original value. Reversible for any input.
  esc() { printf '%s' "$1" | sed 's#//#/$()/#g'; }
  {
    echo "// AUTO-GENERATED by scripts/build_ipa.sh — do not edit, do not commit."
    echo "PAL_BASE_URL = $(esc "$W_BASE_URL")"
    echo "PAL_PROVISIONING_KEY = $(esc "$W_KEY")"
  } > "$XCCONFIG"
  echo "==> Widget config: wrote $XCCONFIG"
else
  # No backend: write empty vars (not nothing). The widget target references
  # this file as its base config, so it must exist — empty values resolve the
  # plist to "" and the widget falls back to no backend, same as the app.
  {
    echo "// AUTO-GENERATED by scripts/build_ipa.sh — do not edit, do not commit."
    echo "PAL_BASE_URL ="
    echo "PAL_PROVISIONING_KEY ="
  } > "$XCCONFIG"
  echo "==> Backend: standalone — wrote empty $XCCONFIG"
fi

echo "==> flutter pub get"
flutter pub get >/dev/null

echo "==> Building unsigned release (this takes a few minutes)..."
flutter build ios --release --no-codesign ${DEFINES[@]+"${DEFINES[@]}"}

echo "==> Packaging .ipa"
rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR/Payload"
cp -R "$APP" "$OUT_DIR/Payload/"
( cd "$OUT_DIR" && /usr/bin/zip -qr Opal.ipa Payload && rm -rf Payload )

echo ""
echo "✓ Built $ROOT/$OUT_DIR/Opal.ipa"
ls -lh "$OUT_DIR/Opal.ipa"
echo ""
echo "Next: open AltStore on your iPhone -> My Apps -> '+' -> pick Opal.ipa"
echo "(or drop it onto AltServer). AltStore signs it with your Apple ID."
